### PR TITLE
fix hoverEvent translation from 1.20.2 to 1.20.3

### PR DESCRIPTION
**Pull request by isjerryxiao**
This fixes `/tp ~ ~ ~` crash on 1.20.3+ client connecting to 1.20.2- servers

### CODE REVIEW

**Comment by kennytv** [comment]
Can't reproduce any issues here, what does this aim at fixing? Having a number in the name field?

**Comment by isjerryxiao** [comment]
> Can't reproduce any issues here, what does this aim at fixing? Having a number in the name field?

If I don't specifically handle the name tag that became a compound tag such as `{'type": "text", "text": "someusername"}`. Now that I looked at the translation code I didn't see a place where that could happen (I was running a fabric 1.20 server and a 1.20.4 fabric client with viafabric). It must be 1.20 server sending that as the name tag. And I still don't know how this patch fixed that issue. Further investigation is required.

**Comment by isjerryxiao** [comment]
```
{
  "translate": "commands.teleport.success.location.single",
  "with": [
    {
      "insertion": "Notch",
      "clickEvent": {
        "action": "suggest_command",
        "value": "/tell Notch "
      },
      "hoverEvent": {
        "action": "show_entity",
        "contents": {
          "type": "minecraft:player",
          "id": "35905f35-d07b-4858-bd94-45ab663a1925",
          "name": {
            "text": "Notch"
          }
        }
      },
      "text": "Notch"
    },
    "0.762684",
    "0.000000",
    "-1.071000"
  ]
}
```
This is the json I got from the 1.20 server.  

```
[00:00:00] [Netty Epoll Client IO #2/ERROR]: onExceptionCaught:
io.netty.handler.codec.DecoderException: Failed to decode: Not a map: null {translate:"commands.teleport.success.location.single",type:"translatable",with:[{clickEvent:{action:"suggest_command",value:"/tell Notch "},hoverEvent:{action:"show_entity",contents:{name:{text:"Notch",type:"text"},type:"minecraft:player"}},insertion:"Notch",text:"Notch",type:"text"},{text:"1.321607",type:"text"},{text:"0.000000",type:"text"},{text:"-1.801685",type:"text"}]}
	at net.minecraft.class_2540.method_34070(class_2540.java:124) ~[client-intermediary.jar:?]
	at net.minecraft.class_156.method_47526(class_156.java:1005) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_29171(class_2540.java:124) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_52954(class_2540.java:118) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_54148(class_2540.java:501) ~[client-intermediary.jar:?]
	at net.minecraft.class_7439.<init>(class_7439.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:513) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539$class_8698.method_52923(class_2539.java:604) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:35) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-classes-epoll-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
This is the error I got on the 1.20.4 client with unpatched viaversion. It could be uuid causing the problem. However the stack trace is useless at best.

**Comment by isjerryxiao** [comment]
It seems that when I changed the patch like this it fixes the problem. But the reason is still unclear to me.

**Review by kennytv — APPROVED** [review]
Thank you for looking into it, the issue is that the json is modified in the first part of `convertJsonArray`, but then tries to convert the already modified json again in the lower part of the array type conversion. Your change fixes it because it does not modify the original json, which is good

We plan on probably replacing most of the conversion anyways to make it handle invalid input better as well, but this works for now

**Pull request merged**
