### PR TITLE
Fix item_name<->default name priority for items in 1.21->1.21.2

### PR DESCRIPTION
**Pull request by FlorianMichael**
Minecraft 1.21.1 client:
custom_name > item_name > default/generated (e.g. player heads/potions)

Minecraft 1.21.2 client:
custom name > default/generated > item_name

### CODE REVIEW

**Review by kennytv — CHANGES_REQUESTED** [review]
This should only be done for the items that need it

**Comment by FlorianMichael** [comment]
Why?

**Comment by kennytv** [comment]
It's unnecessary messing with item data and extra work when only like 3 types of items actually need it. The custom name is used for a lot of other things on the client

**Comment by FlorianMichael** [comment]
Makes sense, done

**Review by kennytv — APPROVED** [review]

**Pull request merged**
