### PR TITLE
Tidy up fabric.mod.json file of fabric platform

### PR DESCRIPTION
**Pull request by FlorianMichael**
ViaVersion will only work with ViaFabric so we should require it.

### CODE REVIEW

**Comment by FlorianMichael** [comment]
On ViaFabricPlus ViaVersion will only do something if putted into the jars folder, it won't do anything as a Mod itself.

**Comment by HowardZHY** [comment]
> On ViaFabricPlus ViaVersion will only do something if putted into the jars folder, it won't do anything as a Mod itself.

Won't that cause something when jar in jar?

**Comment by FlorianMichael** [comment]
No, VFP allows you to replace the jar in jar packaged VV jar on load using the jars folder, but VFP will ignore any Via* jar in the mods folder

**Comment by HowardZHY** [comment]
> > On ViaFabricPlus ViaVersion will only do something if putted into the jars folder, it won't do anything as a Mod itself.
> 
> Won't this cause something wrong when jar in jar?

Fine, it's viaversion-common and it's fabric.mod.json isn't this

**Review by Kichura — APPROVED** [review]

**Pull request merged**
