### PR TITLE
Add Missing Translate Mapping

### PR DESCRIPTION
**Pull request by LemonCaramel**
This PR adds missing translate mapping

### CODE REVIEW

**Comment by LemonCaramel** [comment]
If you don't like my PR, I want you to close it or tell me.
My server has a lot of very young friends who can't read English, so I opened this PR.

**Comment by KennyTV** [comment]
Sorry, this went by our radar. Testing this would be a bit iffy - did you make sure those keys are all correct (and the whitelist ones in 1.12->13) work?

**Comment by LemonCaramel** [comment]
All keys are correct except `block.minecraft.spawn.not_valid` and `item.minecraft(type)_skull`.
For `block.minecraft.spawn.not_valid`, Respawn Anchor was added.
Skull got the name of the block. Skull does have the same meaning.

1.12 to 1.13 Whitelist works fine.

**Review by KennyTV — APPROVED** [review]
Thank you.

**Pull request merged**
