### PR TITLE
Changed "fix-1_21-placement-rotation" to true by default

### PR DESCRIPTION
**Pull request by Pro4D**
Changes the config option "fix-1_21-placement-rotation" to true by default in order to restore vanilla behavior.

### CODE REVIEW

**Comment by Kichura** [comment]
> Changes the config option "fix-1_21-placement-rotation" to true by default in order to restore vanilla behavior.

While this does restore vanilla behavior, this is false on purpose because of anti-cheat plugins. therefore this PR is concerning.

**Comment by Pro4D** [comment]
Are there any explicit examples of what problems this would cause for anti-cheat plugins? And which ones?

**Review by Firecrest-1337 — APPROVED** [review]
I’ve tested this on my own server and it seems to work fine, the only issue i see is that it may accidentally flag anti cheat but definitely not in any major way, especially considering they usually get flagged anyway for unrelated things. I think this should get implemented because liquid behaviour is really really important for pvp.

**Review by FlorianMichael — APPROVED** [review]
Sounds reasonable

**Pull request merged**
