### PR TITLE
Added Runtime-Information to dump (implements #1519)

### PR DESCRIPTION
**Pull request by PierreSchwang**
The ViaDump now includes the runtime information like max, total and free memory.

Example Dump: https://dump.viaversion.com/9b281a34098d3743b6e988b6237b3715fd9a471b24f250616e519df69b691b78

Currently the unit for the memory is bytes - maybe KB / MB should be used instead? I don't know what would be the smartest solution

### CODE REVIEW

**Comment by Camotoy** [comment]
I would do MB, since that's generally regarded as the balance of readable and flexibility of modification.

**Comment by PierreSchwang** [comment]
The generated dump for latest change: https://dump.viaversion.com/a54a66d0ab0d4a8c64446852e540f7ebc971d3ecfdf3fee78bfc56b713433d56

Relevant parts are:
```json
"runtimeInfo":{
   "maxMemory": 7456.948224,
   "freeMemory": 294.53928,
   "totalMemory": 524.288,
   "memoryInfo": "229.7487MB / 524.2880MB (7456.9482MB Max)"
}
```

The raw memory values are not limited to their decimal places, the memoryInfo (formatted data) is limited to 4 decimal places each (Defined in RuntimeInfo L24)

**Review by Kichura — APPROVED** [review]

**Comment by PierreSchwang** [comment]
@Kichura I have mergedthe changes since the creation of the PR because you approved

**Comment by kennytv** [comment]
Memory information isn't actually too useful

**Pull request closed without merging**
