### PR TITLE
fix block connection on non-full chunks

### LINKED ISSUE #2296: Explosions cause ghost blocks to appear
**Describe the bug, provide any errors**
Explosions cause ghost blocks to appear.

**How can we reproduce it?**
1. Log in with 1.16.5 client
2. Place down a few blocks of tnt
3. Ignite them

**Expected behaviour**
No ghost blocks should appear.

**ViaVersion Dump**
https://dump.viaversion.com/281acdfa5e9b8b71c4002bede179a6bfd8efdf536a9c951e68d2022fe27ad058

**Additional server info**
- The same issue does not occur with Spigot.
- Disabling `serverside-blockconnections` option seems to fix the issue.

### PR DESCRIPTION
**Pull request by creeper123123321**
fix #2296

### CODE REVIEW

**Comment by creeper123123321** [comment]
works.

**Review by Kichura — APPROVED** [review]
works here aswell.

**Review by RaphiMC — APPROVED** [review]
Works for me, finally this has been fixed

**Comment by kennytv** [comment]
Which parts of the WorldPackets file is actual code diff?

**Review by kennytv — CHANGES_REQUESTED** [review]
Disable block connections and 💥

**Comment by Kichura** [comment]
> Disable block connections and 💥

java code goes brrrrr.

**Comment by kennytv** [comment]
Now it's broken with connections *enabled*

**Review by kennytv — APPROVED** [review]
Should be fine:tm:

**Pull request merged**
