### PR TITLE
use a more fork-proof approach to enable Paper block place patch

### PR DESCRIPTION
**Pull request by tomcraft**
tested with:
 - Paper 1.8.8, 1.9.4, 1.11.2 (enabling)
 - SportPaper 1.8.8 (enabling)
 - Spigot 1.8.8 (not enabling)

### CODE REVIEW

**Review by Xernium — APPROVED** [review]

**Comment by FormallyMyles** [comment]
Code looks great, however, do we also need a way to disable the patch? Given that some forks can remove the faulty code.

**Comment by tomcraft** [comment]
I added a system property to disable this patch, is it an ok-enough approach ?

**Comment by FormallyMyles** [comment]
> I added a system property to disable this patch, is it an ok-enough approach ?

I don't see any issue with that, also means the fork could control it if they wanted to

**Review by FormallyMyles — APPROVED** [review]

**Comment by andreasdc** [comment]
Oh no, what if someone doesn't want this patch? It's buggy.

**Comment by kennytv** [comment]
Then you put the system property `com.viaversion.ignorePaperBlockPlacePatch` as `true`

**Comment by andreasdc** [comment]
Oh yes I didn't see this commit, It would be cool to have that in config too.

**Comment by andreasdc** [comment]
So basically '-com.viaversion.ignorePaperBlockPlacePatch=true' in flags?

**Comment by tomcraft** [comment]
-Dcom.viaversion.ignorePaperBlockPlacePatch=true

**Comment by andreasdc** [comment]
I think having it in the config would be better, also I don't think so you want to add this patch, without additional changes in it creates many bugs.

**Pull request merged**
