### PR TITLE
Rewrite 1.12.2->1.13 ComponentRewriter

### PR DESCRIPTION
**Pull request by FlorianMichael**
Move away from ViaNBT's SNBT parsing and replaces the code with proper MCStructs parsing

### CODE REVIEW

**Comment by FlorianMichael** [comment]
Basically https://github.com/ViaVersion/ViaVersion/pull/3740 but for the next protocol, at some point I'll maybe need to implement proper chat item rewriter into all protocols so chat items are working.

**Comment by kennytv** [comment]
Any examples of what this actually fixes?

**Comment by FlorianMichael** [comment]
The findItemNBT would cause the same issue as in https://github.com/ViaVersion/ViaVersion/pull/3740 since it doesn't handle most cases. I also replaced ViaNBT's SNBT parser since it doesn't handle version differences which exists properly, I have no compound at the moment but all changes between 1.12.2 and 1.13 wouldn't be probably handled without MCStructs. We are already using MCStructs when parsing SNBT/Text components everywhere else so there is no reason for us to not do it in here too, I also tried some cursed nbts and they are working with the PR's changes.

**Comment by FlorianMichael** [comment]
Here is an example nbt which will cause the old code to crash:
`/tellraw @a {"text":"Guter Text","hoverEvent":{"action":"show_item","value":{"text": "{", "extra": [{"text": "id:stone,Damage:1,Count:1}"}]}}}`

**Review by kennytv — APPROVED** [review]

**Pull request merged**
